/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesaRouteImport } from './routes/mesa'
import { Route as MestreRouteImport } from './routes/mestre'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as RoladorRouteImport } from './routes/rolador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaRoute = MesaRouteImport.update({
  id: '/mesa',
  path: '/mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const MestreRoute = MestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const RoladorRoute = RoladorRouteImport.update({
  id: '/rolador',
  path: '/rolador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mesa': typeof MesaRoute
  '/mestre': typeof MestreRoute
  '/regras': typeof RegrasRoute
  '/rolador': typeof RoladorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mesa': typeof MesaRoute
  '/mestre': typeof MestreRoute
  '/regras': typeof RegrasRoute
  '/rolador': typeof RoladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mesa': typeof MesaRoute
  '/mestre': typeof MestreRoute
  '/regras': typeof RegrasRoute
  '/rolador': typeof RoladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mesa' | '/mestre' | '/regras' | '/rolador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mesa' | '/mestre' | '/regras' | '/rolador'
  id: '__root__' | '/' | '/mesa' | '/mestre' | '/regras' | '/rolador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MesaRoute: typeof MesaRoute
  MestreRoute: typeof MestreRoute
  RegrasRoute: typeof RegrasRoute
  RoladorRoute: typeof RoladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa': {
      id: '/mesa'
      path: '/mesa'
      fullPath: '/mesa'
      preLoaderRoute: typeof MesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestre': {
      id: '/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof MestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolador': {
      id: '/rolador'
      path: '/rolador'
      fullPath: '/rolador'
      preLoaderRoute: typeof RoladorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MesaRoute: MesaRoute,
  MestreRoute: MestreRoute,
  RegrasRoute: RegrasRoute,
  RoladorRoute: RoladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
